### PR TITLE
Apply protocol model pattern to missing types in Responses

### LINKED ISSUE #863: Modify ImplicitConversionToBinaryContentVisitor to allow for exception list
We have this [visitor[(https://github.com/openai/openai-dotnet/blob/main/codegen/generator/src/Visitors/ImplicitConversionToBinaryContentVisitor.cs) which removes the generated BinaryContent implicit conversion because it wasn't useful for any of our models:

However, this is definitely useful for our protocol models. Let's modify the visitor so that we can keep a list of types that we can "opt-out" of the visitor, so that this code gets generated instead of having to keep it as custom code.

### PR DESCRIPTION
**Pull request by joseharriaga**
- Added a visitor to generate the protocol model pattern: 1) properties with setters, 2) public default constructor, 3) implicit conversion from `BinaryContent` for input models.
- Applied protocol model pattern to missing types in Responses, including the derived types of `StreamingResponseUpdate`, `ResponseDeletionResult`, and `ResponseItemCollectionPage`.
- Fixed an issue with `CreateResponse` methods overriding the value of `StreamingEnabled`. It is now the responsibility of the user to correctly set `StreamingEnabled` based on if they are calling the streaming or non-streaming method.
- Added validation that checks the value of `StreamingEnabled` based on which method it is being used with and throws an exception in case of invalid combinations.
- Changed the `ConversationId` property in `CreateResponseOptions` to match the `ConversationOptions` property of `ResponseResult`, i.e. type is now `ResponseConversationOptions` instead of just a `string`.
- Renamed `MaxToolCalls` in `CreateResponseOptions` to `MaxToolCallCount` to match the property in `ResponseResult`.
- Renamed `Id` in `ResponseDeletionResult` to `ResponseId` for clarity and consistency with other APIs in the library.
- fixes #863

### CODE REVIEW

File: codegen/generator/src/Visitors/ProtocolModelVisitor.cs [hunk 1]
```diff
@@ -0,0 +1,125 @@
...
+{
+    // Classes that are protocol models.
+    private static readonly HashSet<string> _protocolModels = new(StringComparer.OrdinalIgnoreCase)
+    {
+        "OpenAI.Responses.CreateResponseOptions",
+        "OpenAI.Responses.ResponseDeletionResult",
+        "OpenAI.Responses.ResponseItemCollectionPage",
+        "OpenAI.Responses.ResponseResult",
+
+        // "OpenAI.Responses.StreamingResponseUpdate",
```
Comment (christothes) [inline codegen/generator/src/Visitors/ProtocolModelVisitor.cs]: Is this intentional?

File: codegen/generator/src/OpenAILibraryGenerator.cs [hunk 2]
```diff
@@ -27,12 +27,13 @@ protected override void Configure()
             AddVisitor(new OpenAILibraryVisitor());
             AddVisitor(new VirtualMessageCreationVisitor());
             AddVisitor(new ProhibitedNamespaceVisitor());
-            AddVisitor(new ImplicitConversionToBinaryContentVisitor());
+            // AddVisitor(new ImplicitConversionToBinaryContentVisitor());
```
Comment (christothes) [inline codegen/generator/src/OpenAILibraryGenerator.cs]: Should we remove this and the visitor?

File: src/Custom/Responses/Streaming/StreamingResponseContentPartAddedUpdate.cs [hunk 3]
```diff
@@ -1,14 +1,10 @@
...
-// - Added Experimental attribute.
-// - Renamed.
+// CUSTOM: Renamed.
 [CodeGenType("ResponseContentPartAddedEvent")]
 public partial class StreamingResponseContentPartAddedUpdate
 {
     // CUSTOM: Apply generalized content type.
     [CodeGenMember("Part")]
-    public ResponseContentPart Part { get; }
+    public ResponseContentPart Part { get; set; }
```
Comment (christothes) [inline src/Custom/Responses/Streaming/StreamingResponseContentPartAddedUpdate.cs:9]: Will the `ProtocolModelVisitor` do this for us?

File: src/Custom/Responses/Streaming/StreamingResponseContentPartDoneUpdate.cs [hunk 4]
```diff
@@ -1,14 +1,10 @@
...
-// - Added Experimental attribute.
-// - Renamed.
+// CUSTOM: Renamed.
 [CodeGenType("ResponseContentPartDoneEvent")]
 public partial class StreamingResponseContentPartDoneUpdate
 {
     // CUSTOM: Apply generalized content type.
     [CodeGenMember("Part")]
-    public ResponseContentPart Part { get; }
+    public ResponseContentPart Part { get; set; }
```
Comment (christothes) [inline src/Custom/Responses/Streaming/StreamingResponseContentPartDoneUpdate.cs:9]: Will the `ProtocolModelVisitor` do this for us?

File: src/Custom/Responses/Streaming/StreamingResponseUpdate.cs [hunk 5]
```diff
@@ -1,12 +1,11 @@
...
-// - Added Experimental attribute.
-// - Renamed.
+// CUSTOM: Renamed.
 [CodeGenType("ResponseStreamEvent")]
 [CodeGenSuppress("StreamingResponseUpdate", typeof(System.ClientModel.ClientResult))]
 public partial class StreamingResponseUpdate
 {
+    // CUSTOM: Added setter because this is a property of protocol model.
+    [CodeGenMember("SequenceNumber")]
+    public int SequenceNumber { get; set; }
```
Comment (christothes) [inline src/Custom/Responses/Streaming/StreamingResponseUpdate.cs]: Will the `ProtocolModelVisitor` do this for us?

File: api/OpenAI.net8.0.cs [hunk 6]
```diff
@@ -5896,13 +5900,12 @@ public class ResponseItem : IJsonModel<ResponseItem>, IPersistableModel<Response
...
     [Experimental("OPENAI001")]
     public class ResponseItemCollectionOptions : IJsonModel<ResponseItemCollectionOptions>, IPersistableModel<ResponseItemCollectionOptions> {
-        public ResponseItemCollectionOptions();
         public ResponseItemCollectionOptions(string responseId);
         public string AfterId { get; set; }
         public string BeforeId { get; set; }
         public ResponseItemCollectionOrder? Order { get; set; }
         public int? PageSizeLimit { get; set; }
-        public string ResponseId { get; set; }
+        public string ResponseId { get; }
```
Comment (christothes) [inline api/OpenAI.net8.0.cs:5908]: Is this intentional?

File: codegen/generator/src/Visitors/ProtocolModelVisitor.cs (hunk 1 above)
Comment (joseharriaga) [reply codegen/generator/src/Visitors/ProtocolModelVisitor.cs]: I originally excluded `StreamingResponseUpdate` from this list because the visitor would make its default constructor public, but because this is the base type in a hierarchy, I think its default constructor should remain internal. Instead, the default constructor must be exposed in the derived types only. With Jorge's help, I found a fix to be able to do this with the visitor, and `StreamingResponseUpdate` can be included in this list. 🙂

File: codegen/generator/src/OpenAILibraryGenerator.cs (hunk 2 above)
Comment (joseharriaga) [reply codegen/generator/src/OpenAILibraryGenerator.cs]: Yes. Fixed!

File: src/Custom/Responses/Streaming/StreamingResponseUpdate.cs (hunk 5 above)
Comment (joseharriaga) [reply src/Custom/Responses/Streaming/StreamingResponseUpdate.cs]: This is now possible with the fix I just added to the visitor to be able to handle `StreamingResponseUpdate`. Fixed!

File: src/Custom/Responses/Streaming/StreamingResponseContentPartAddedUpdate.cs (hunk 3 above)
Comment (joseharriaga) [reply src/Custom/Responses/Streaming/StreamingResponseContentPartAddedUpdate.cs:9]: It will once this property is moved to generated code, but for now it needs to remain in custom code for reasons unrelated to this change (i.e., to apply the generalized ResponseContentPart type as per the CUSTOM comment). I suspect we can fix it with client.tsp, but we can do it separately in the future.

File: src/Custom/Responses/Streaming/StreamingResponseContentPartDoneUpdate.cs (hunk 4 above)
Comment (joseharriaga) [reply src/Custom/Responses/Streaming/StreamingResponseContentPartDoneUpdate.cs:9]: It will once this property is moved to generated code, but for now it needs to remain in custom code for reasons unrelated to this change (i.e., to apply the generalized ResponseContentPart type as per the CUSTOM comment). I suspect we can fix it with client.tsp, but we can do it separately in the future.

File: api/OpenAI.net8.0.cs (hunk 6 above)
Comment (joseharriaga) [reply api/OpenAI.net8.0.cs:5908]: For now, yes. Here's my reasoning: `ResponseItemCollectionOptions` is technically not a protocol model. Instead, it is a property bag that we invented to wrap path and query parameter. At this moment, we're still unsure what path we want to take with these: Should they behave like "status quo" models? Or should they behave like protocol models? Or should they behave in their own way?

The change I'm making here is to make them behave the "status quo" way, which I think is the safest for now while we close on the design.

**Review by christothes — APPROVED** [review]
